ocac_course_catalog:
  path: api/v1/{org}/{term}/courses
  defaults: { _controller: OCACBundle:CourseCatalog:index }

ocac_course_list:
  path: api/v1/{org}/{term}/course
  defaults: { _controller: OCACBundle:CourseCatalog:index }

ocac_course:
  path: api/v1/{org}/{term}/course/{section_id}
  defaults: { _controller: OCACBundle:CourseCatalog:course }

ocac_add_class:
    path:     api/v1/student/{student_id}/classes/add/{section_id}
    defaults: { _controller: OCACBundle:Scheduling:addClass }
    methods: [POST]

ocac_delete_class:
    path:     api/v1/student/{student_id}/classes/{class_id}
    defaults: { _controller: OCACBundle:Scheduling:removeClass }
    methods: [DELETE]

ocac_classes:
    path:     api/v1/student/{student_id}/classes
    defaults: { _controller: OCACBundle:Scheduling:getClasses }
    methods: [GET]

ocac_classes_org_term:
    path:     api/v1/student/{student_id}/classes/{org}/{term}
    defaults: { _controller: OCACBundle:Scheduling:getClasses }
    methods: [GET]

ocac_user_children:
    path:     api/v1/user/current/children
    defaults: { _controller: OCACBundle:User:getChildren }
    methods: [GET]

ocac_user_children_add:
    path:     api/v1/user/current/children/add
    defaults: { _controller: OCACBundle:User:addChild }
    methods: [POST]